doctrine:
    dbal:
        default_connection: mariadb
        connections:
            mariadb:
                # configure these for your database server
                driver: 'pdo_mysql'
                server_version: 'mariadb-10.4.8'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                host: 'mariadb'
                user: 'ips2019'
                password: 'ips2019'
                dbname: 'ips2019'
            clickhouse:
                host:     localhost
                port:     8123
                user:     default
                password: ""
                dbname:   'test'
                driver_class: FOD\DBALClickHouse\Driver
                wrapper_class: FOD\DBALClickHouse\Connection
                options:
                    enable_http_compression: 1
                    max_execution_time: 60
