version: '3.7'

services:
  php-fpm:
    build:
       dockerfile: ./docker/php-fpm/Dockerfile
       context: ./
    volumes:
      - ./:/var/www/html:cached

  nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    ports:
      - "8080:80"

  mariadb:
      container_name: mariadb
      image: mariadb:10.4
      restart: always
      volumes:
        - ./sql/createDatabase:/docker-entrypoint-initdb.d
        - ./sql:/sql_dump
      environment:
        MYSQL_ROOT_PASSWORD: test123
        MYSQL_DATABASE: ips2019
        MYSQL_USER: ips2019
        MYSQL_PASSWORD: ips2019
      ports:
        - "3305:3306"
      expose:
        - '3306'
        - '3305'

  clickhouse:
      container_name: clickhouse
      image: yandex/clickhouse-server
      ports:
        - "8123:8123"
        - "9000:9000"

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin-bridge
      restart: always
      depends_on:
        - mariadb
      ports:
        - "30002:80"
      environment:
        PMA_HOST: mariadb
        MYSQL_ROOT_PASSWORD: 'ips2019'
      volumes:
        - /sessions
