version: '3.7'

services:
  php-fpm:
    build:
       context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html:cached

  nginx:
    image: nginx:stable
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html
    ports:
      - "80:80"

  mariadb:
      container_name: mariadb
      build:
        context: ./docker/mariadb
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: ips2019
        MYSQL_USER: ips2019
        MYSQL_PASSWORD: ips2019
      ports:
        - "3306:3306"

  clickhouse:
      container_name: clickhouse
      image: yandex/clickhouse-server
      ports:
        - "8123:8123"
        - "9000:9000"

volumes:
  mariadb:
  clickhouse: